### ISSUE TITLE
Test issue in MS Edge

### ISSUE THREAD

**Issue by YorkHorten** [zenozeng/p5.js-svg#128] opened 2015-08-16 07:11 UTC
![image](https://cloud.githubusercontent.com/assets/6824088/9292399/005a4fde-4429-11e5-940e-e9219270228d.png)

**Comment by zenozeng** [comment] 2016-01-25 16:52
Can't reproduce in MS Edge 25, so won't fix.

**Closed by zenozeng** 2016-01-25 16:52 UTC
Labels: bug, wontfix
